# proto-file: config.proto
# proto-message: UprobestatsConfig

tasks {
    probe_configs {
        bpf_name: "prog_BinderExecTransactInternal_uprobe_activity_task_manager_startActivity"
        fully_qualified_class_name: "android.os.Binder"
        method_name: "execTransactInternal"
        fully_qualified_parameters: ["int", "android.os.Parcel", "android.os.Parcel", "int", "int"]
    }
    bpf_maps: "map_BinderExecTransactInternal_output_buf"
    target_process_name: "system_server"
    duration_seconds: 60
}
